// constants/permissions.ts
export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard:view",

  SALES_CUSTOMERS_VIEW: "sales:customers:view",
  SALES_CUSTOMERS_CREATE: "sales:customers:create",
  SALES_CUSTOMERS_EDIT: "sales:customers:edit",
  SALES_CUSTOMERS_APPROVE: "sales:customers:approve",
  SALES_CUSTOMERS_DELETE: "sales:customers:delete",
  SALES_CUSTOMERS_EXPORT: "sales:customers:export",

  SALES_INVOICES_VIEW: "sales:invoices:view",
  SALES_INVOICES_CREATE: "sales:invoices:create",
  SALES_INVOICES_EDIT: "sales:invoices:edit",
  SALES_INVOICES_APPROVE: "sales:invoices:approve",
  SALES_INVOICES_DELETE: "sales:invoices:delete",
  SALES_INVOICES_EXPORT: "sales:invoices:export",

  SALES_PAYMENT_RECEIVED_VIEW: "sales:paymentRecieved:view",
  SALES_PAYMENT_RECEIVED_CREATE: "sales:paymentRecieved:create",
  SALES_PAYMENT_RECEIVED_EDIT: "sales:paymentRecieved:edit",
  SALES_PAYMENT_RECEIVED_APPROVE: "sales:paymentRecieved:approve",
  SALES_PAYMENT_RECEIVED_DELETE: "sales:paymentRecieved:delete",
  SALES_PAYMENT_RECEIVED_EXPORT: "sales:paymentRecieved:export",

  SALES_CREDIT_NOTES_VIEW: "sales:creditNotes:view",
  SALES_CREDIT_NOTES_CREATE: "sales:creditNotes:create",
  SALES_CREDIT_NOTES_EDIT: "sales:creditNotes:edit",
  SALES_CREDIT_NOTES_APPROVE: "sales:creditNotes:approve",
  SALES_CREDIT_NOTES_DELETE: "sales:creditNotes:delete",
  SALES_CREDIT_NOTES_EXPORT: "sales:creditNotes:export",

  PURCHASES_BILLS_VIEW: "purchases:bills:view",
  PURCHASES_BILLS_CREATE: "purchases:bills:create",
  PURCHASES_BILLS_EDIT: "purchases:bills:edit",
  PURCHASES_BILLS_APPROVE: "purchases:bills:approve",
  PURCHASES_BILLS_DELETE: "purchases:bills:delete",
  PURCHASES_BILLS_EXPORT: "purchases:bills:export",

  PURCHASES_PAYMENT_MADE_VIEW: "purchases:paymentMade:view",
  PURCHASES_PAYMENT_MADE_CREATE: "purchases:paymentMade:create",
  PURCHASES_PAYMENT_MADE_EDIT: "purchases:paymentMade:edit",
  PURCHASES_PAYMENT_MADE_APPROVE: "purchases:paymentMade:approve",
  PURCHASES_PAYMENT_MADE_DELETE: "purchases:paymentMade:delete",
  PURCHASES_PAYMENT_MADE_EXPORT: "purchases:paymentMade:export",

  PURCHASES_DEBIT_NOTES_VIEW: "purchases:debitNotes:view",
  PURCHASES_DEBIT_NOTES_CREATE: "purchases:debitNotes:create",
  PURCHASES_DEBIT_NOTES_EDIT: "purchases:debitNotes:edit",
  PURCHASES_DEBIT_NOTES_APPROVE: "purchases:debitNotes:approve",
  PURCHASES_DEBIT_NOTES_DELETE: "purchases:debitNotes:delete",
  PURCHASES_DEBIT_NOTES_EXPORT: "purchases:debitNotes:export",

  PURCHASES_EXPENSES_VIEW: "purchases:expenses:view",
  PURCHASES_EXPENSES_CREATE: "purchases:expenses:create",
  PURCHASES_EXPENSES_EDIT: "purchases:expenses:edit",
  PURCHASES_EXPENSES_APPROVE: "purchases:expenses:approve",
  PURCHASES_EXPENSES_DELETE: "purchases:expenses:delete",
  PURCHASES_EXPENSES_EXPORT: "purchases:expenses:export",

  PURCHASES_VENDORS_VIEW: "purchases:vendors:view",
  PURCHASES_VENDORS_CREATE: "purchases:vendors:create",
  PURCHASES_VENDORS_EDIT: "purchases:vendors:edit",
  PURCHASES_VENDORS_APPROVE: "purchases:vendors:approve",
  PURCHASES_VENDORS_DELETE: "purchases:vendors:delete",
  PURCHASES_VENDORS_EXPORT: "purchases:vendors:export",

  PRODUCTS_ITEMS_VIEW: "products:items:view",
  PRODUCTS_ITEMS_CREATE: "products:items:create",
  PRODUCTS_ITEMS_EDIT: "products:items:edit",
  PRODUCTS_ITEMS_APPROVE: "products:items:approve",
  PRODUCTS_ITEMS_DELETE: "products:items:delete",
  PRODUCTS_ITEMS_EXPORT: "products:items:export",

  PRODUCTS_COLLECTIONS_VIEW: "products:collections:view",
  PRODUCTS_COLLECTIONS_CREATE: "products:collections:create",
  PRODUCTS_COLLECTIONS_EDIT: "products:collections:edit",
  PRODUCTS_COLLECTIONS_APPROVE: "products:collections:approve",
  PRODUCTS_COLLECTIONS_DELETE: "products:collections:delete",
  PRODUCTS_COLLECTIONS_EXPORT: "products:collections:export",

  PRODUCTS_INVENTORY_VIEW: "products:inventory:view",
  PRODUCTS_INVENTORY_CREATE: "products:inventory:create",
  PRODUCTS_INVENTORY_EDIT: "products:inventory:edit",
  PRODUCTS_INVENTORY_APPROVE: "products:inventory:approve",
  PRODUCTS_INVENTORY_DELETE: "products:inventory:delete",
  PRODUCTS_INVENTORY_EXPORT: "products:inventory:export",

  PRODUCTS_ORDERS_VIEW: "products:orders:view",
  PRODUCTS_ORDERS_CREATE: "products:orders:create",
  PRODUCTS_ORDERS_EDIT: "products:orders:edit",
  PRODUCTS_ORDERS_APPROVE: "products:orders:approve",
  PRODUCTS_ORDERS_DELETE: "products:orders:delete",
  PRODUCTS_ORDERS_EXPORT: "products:orders:export",

  QUICK_SALE_VIEW: "quickSale:quickSale:view",
  QUICK_SALE_CREATE: "quickSale:quickSale:create",
  QUICK_SALE_EDIT: "quickSale:quickSale:edit",
  QUICK_SALE_APPROVE: "quickSale:quickSale:approve",
  QUICK_SALE_DELETE: "quickSale:quickSale:delete",
  QUICK_SALE_EXPORT: "quickSale:quickSale:export",

  ONLINE_STORE_MANAGEMENT_VIEW: "onlineStore:onlineStoreManagement:view",
  ONLINE_STORE_MANAGEMENT_CREATE: "onlineStore:onlineStoreManagement:create",
  ONLINE_STORE_MANAGEMENT_EDIT: "onlineStore:onlineStoreManagement:edit",
  ONLINE_STORE_MANAGEMENT_APPROVE: "onlineStore:onlineStoreManagement:approve",
  ONLINE_STORE_MANAGEMENT_DELETE: "onlineStore:onlineStoreManagement:delete",
  ONLINE_STORE_MANAGEMENT_EXPORT: "onlineStore:onlineStoreManagement:export",

  ASSETS_VIEW: "assets:view",
  ASSETS_CREATE: "assets:create",
  ASSETS_EDIT: "assets:edit",
  ASSETS_APPROVE: "assets:approve",
  ASSETS_DELETE: "assets:delete",
  ASSETS_EXPORT: "assets:export",

  HR_EMPLOYEES_VIEW: "hrAndPayroll:employees:view",
  HR_EMPLOYEES_CREATE: "hrAndPayroll:employees:create",
  HR_EMPLOYEES_EDIT: "hrAndPayroll:employees:edit",
  HR_EMPLOYEES_APPROVE: "hrAndPayroll:employees:approve",
  HR_EMPLOYEES_DELETE: "hrAndPayroll:employees:delete",
  HR_EMPLOYEES_EXPORT: "hrAndPayroll:employees:export",

  HR_ATTENDANCE_VIEW: "hrAndPayroll:attendance:view",
  HR_ATTENDANCE_CREATE: "hrAndPayroll:attendance:create",
  HR_ATTENDANCE_EDIT: "hrAndPayroll:attendance:edit",
  HR_ATTENDANCE_APPROVE: "hrAndPayroll:attendance:approve",
  HR_ATTENDANCE_DELETE: "hrAndPayroll:attendance:delete",
  HR_ATTENDANCE_EXPORT: "hrAndPayroll:attendance:export",

  HR_PAYROLL_VIEW: "hrAndPayroll:payroll:view",
  HR_PAYROLL_CREATE: "hrAndPayroll:payroll:create",
  HR_PAYROLL_EDIT: "hrAndPayroll:payroll:edit",
  HR_PAYROLL_APPROVE: "hrAndPayroll:payroll:approve",
  HR_PAYROLL_DELETE: "hrAndPayroll:payroll:delete",
  HR_PAYROLL_EXPORT: "hrAndPayroll:payroll:export",

  HR_MANAGE_LEAVE_VIEW: "hrAndPayroll:manageLeave:view",
  HR_MANAGE_LEAVE_CREATE: "hrAndPayroll:manageLeave:create",
  HR_MANAGE_LEAVE_EDIT: "hrAndPayroll:manageLeave:edit",
  HR_MANAGE_LEAVE_APPROVE: "hrAndPayroll:manageLeave:approve",
  HR_MANAGE_LEAVE_DELETE: "hrAndPayroll:manageLeave:delete",
  HR_MANAGE_LEAVE_EXPORT: "hrAndPayroll:manageLeave:export",

  ACCOUNTS_CHART_OF_ACCOUNTS_VIEW: "accounts:chartOfAccounts:view",
  ACCOUNTS_CHART_OF_ACCOUNTS_CREATE: "accounts:chartOfAccounts:create",
  ACCOUNTS_CHART_OF_ACCOUNTS_EDIT: "accounts:chartOfAccounts:edit",
  ACCOUNTS_CHART_OF_ACCOUNTS_APPROVE: "accounts:chartOfAccounts:approve",
  ACCOUNTS_CHART_OF_ACCOUNTS_DELETE: "accounts:chartOfAccounts:delete",
  ACCOUNTS_CHART_OF_ACCOUNTS_EXPORT: "accounts:chartOfAccounts:export",

  ACCOUNTS_OPENING_BALANCE_VIEW: "accounts:openingBalance:view",
  ACCOUNTS_OPENING_BALANCE_CREATE: "accounts:openingBalance:create",
  ACCOUNTS_OPENING_BALANCE_EDIT: "accounts:openingBalance:edit",
  ACCOUNTS_OPENING_BALANCE_APPROVE: "accounts:openingBalance:approve",
  ACCOUNTS_OPENING_BALANCE_DELETE: "accounts:openingBalance:delete",
  ACCOUNTS_OPENING_BALANCE_EXPORT: "accounts:openingBalance:export",

  ACCOUNTS_MANUAL_JOURNAL_VIEW: "accounts:manualJournal:view",
  ACCOUNTS_MANUAL_JOURNAL_CREATE: "accounts:manualJournal:create",
  ACCOUNTS_MANUAL_JOURNAL_EDIT: "accounts:manualJournal:edit",
  ACCOUNTS_MANUAL_JOURNAL_APPROVE: "accounts:manualJournal:approve",
  ACCOUNTS_MANUAL_JOURNAL_DELETE: "accounts:manualJournal:delete",
  ACCOUNTS_MANUAL_JOURNAL_EXPORT: "accounts:manualJournal:export",

  ACCOUNTS_CURRENCY_ADJUSTMENT_VIEW: "accounts:currencyAdjustment:view",
  ACCOUNTS_CURRENCY_ADJUSTMENT_CREATE: "accounts:currencyAdjustment:create",
  ACCOUNTS_CURRENCY_ADJUSTMENT_EDIT: "accounts:currencyAdjustment:edit",
  ACCOUNTS_CURRENCY_ADJUSTMENT_APPROVE: "accounts:currencyAdjustment:approve",
  ACCOUNTS_CURRENCY_ADJUSTMENT_DELETE: "accounts:currencyAdjustment:delete",
  ACCOUNTS_CURRENCY_ADJUSTMENT_EXPORT: "accounts:currencyAdjustment:export",

  ACCOUNTS_BUDGET_VIEW: "accounts:Budget:view",
  ACCOUNTS_BUDGET_CREATE: "accounts:Budget:create",
  ACCOUNTS_BUDGET_EDIT: "accounts:Budget:edit",
  ACCOUNTS_BUDGET_APPROVE: "accounts:Budget:approve",
  ACCOUNTS_BUDGET_DELETE: "accounts:Budget:delete",
  ACCOUNTS_BUDGET_EXPORT: "accounts:Budget:export",

  // BANKING_OVERVIEW_VIEW: "banking:bankingOverview:view",
  // BANKING_OVERVIEW_CREATE: "banking:bankingOverview:create",
  // BANKING_OVERVIEW_EDIT: "banking:bankingOverview:edit",
  // BANKING_OVERVIEW_APPROVE: "banking:bankingOverview:approve",
  // BANKING_OVERVIEW_DELETE: "banking:bankingOverview:delete",
  // BANKING_OVERVIEW_EXPORT: "banking:bankingOverview:export",

  // BANKING_BANK_ACCOUNTS_VIEW: "banking:bankAccounts:view",
  // BANKING_BANK_ACCOUNTS_CREATE: "banking:bankAccounts:create",
  // BANKING_BANK_ACCOUNTS_EDIT: "banking:bankAccounts:edit",
  // BANKING_BANK_ACCOUNTS_APPROVE: "banking:bankAccounts:approve",
  // BANKING_BANK_ACCOUNTS_DELETE: "banking:bankAccounts:delete",
  // BANKING_BANK_ACCOUNTS_EXPORT: "banking:bankAccounts:export",

  // BANKING_RECONCILIATION_VIEW: "banking:reconciliation:view",
  // BANKING_RECONCILIATION_CREATE: "banking:reconciliation:create",
  // BANKING_RECONCILIATION_EDIT: "banking:reconciliation:edit",
  // BANKING_RECONCILIATION_APPROVE: "banking:reconciliation:approve",
  // BANKING_RECONCILIATION_DELETE: "banking:reconciliation:delete",
  // BANKING_RECONCILIATION_EXPORT: "banking:reconciliation:export",

  BANKING_VIEW: "banking:view",

  // REPORTS_CENTER_VIEW: "reports:reportsCenter:view",
  // REPORTS_CENTER_CREATE: "reports:reportsCenter:create",
  // REPORTS_CENTER_EDIT: "reports:reportsCenter:edit",
  // REPORTS_CENTER_APPROVE: "reports:reportsCenter:approve",
  // REPORTS_CENTER_DELETE: "reports:reportsCenter:delete",
  // REPORTS_CENTER_EXPORT: "reports:reportsCenter:export",

  // REPORTS_PROFIT_AND_LOSS_VIEW: "reports:profitAndLoss:view",
  // REPORTS_PROFIT_AND_LOSS_CREATE: "reports:profitAndLoss:create",
  // REPORTS_PROFIT_AND_LOSS_EDIT: "reports:profitAndLoss:edit",
  // REPORTS_PROFIT_AND_LOSS_APPROVE: "reports:profitAndLoss:approve",
  // REPORTS_PROFIT_AND_LOSS_DELETE: "reports:profitAndLoss:delete",
  // REPORTS_PROFIT_AND_LOSS_EXPORT: "reports:profitAndLoss:export",

  // REPORTS_BALANCE_SHEET_VIEW: "reports:balanceSheet:view",
  // REPORTS_BALANCE_SHEET_CREATE: "reports:balanceSheet:create",
  // REPORTS_BALANCE_SHEET_EDIT: "reports:balanceSheet:edit",
  // REPORTS_BALANCE_SHEET_APPROVE: "reports:balanceSheet:approve",
  // REPORTS_BALANCE_SHEET_DELETE: "reports:balanceSheet:delete",
  // REPORTS_BALANCE_SHEET_EXPORT: "reports:balanceSheet:export",

  // REPORTS_CASH_FLOW_STATEMENT_VIEW: "reports:cashFlowStatement:view",
  // REPORTS_CASH_FLOW_STATEMENT_CREATE: "reports:cashFlowStatement:create",
  // REPORTS_CASH_FLOW_STATEMENT_EDIT: "reports:cashFlowStatement:edit",
  // REPORTS_CASH_FLOW_STATEMENT_APPROVE: "reports:cashFlowStatement:approve",
  // REPORTS_CASH_FLOW_STATEMENT_DELETE: "reports:cashFlowStatement:delete",
  // REPORTS_CASH_FLOW_STATEMENT_EXPORT: "reports:cashFlowStatement:export",\

  REPORTS_VIEW: "reports:view",

  SETTINGS_ORGANIZATION_VIEW: "settings:organization:view",
  SETTINGS_ORGANIZATION_CREATE: "settings:organization:create",
  SETTINGS_ORGANIZATION_EDIT: "settings:organization:edit",
  SETTINGS_ORGANIZATION_APPROVE: "settings:organization:approve",
  SETTINGS_ORGANIZATION_DELETE: "settings:organization:delete",
  SETTINGS_ORGANIZATION_EXPORT: "settings:organization:export",

  SETTINGS_USERS_AND_ROLES_VIEW: "settings:usersAndRoles:view",
  SETTINGS_USERS_AND_ROLES_CREATE: "settings:usersAndRoles:create",
  SETTINGS_USERS_AND_ROLES_EDIT: "settings:usersAndRoles:edit",
  SETTINGS_USERS_AND_ROLES_APPROVE: "settings:usersAndRoles:approve",
  SETTINGS_USERS_AND_ROLES_DELETE: "settings:usersAndRoles:delete",
  SETTINGS_USERS_AND_ROLES_EXPORT: "settings:usersAndRoles:export",

  SETTINGS_SETUP_AND_CONFIGURATION_VIEW: "settings:setupAndConfiguration:view",
  SETTINGS_SETUP_AND_CONFIGURATION_CREATE:
    "settings:setupAndConfiguration:create",
  SETTINGS_SETUP_AND_CONFIGURATION_EDIT: "settings:setupAndConfiguration:edit",
  SETTINGS_SETUP_AND_CONFIGURATION_APPROVE:
    "settings:setupAndConfiguration:approve",
  SETTINGS_SETUP_AND_CONFIGURATION_DELETE:
    "settings:setupAndConfiguration:delete",
  SETTINGS_SETUP_AND_CONFIGURATION_EXPORT:
    "settings:setupAndConfiguration:export",

  SETTINGS_SALES_SETTINGS_VIEW: "settings:salesSettings:view",
  SETTINGS_SALES_SETTINGS_CREATE: "settings:salesSettings:create",
  SETTINGS_SALES_SETTINGS_EDIT: "settings:salesSettings:edit",
  SETTINGS_SALES_SETTINGS_APPROVE: "settings:salesSettings:approve",
  SETTINGS_SALES_SETTINGS_DELETE: "settings:salesSettings:delete",
  SETTINGS_SALES_SETTINGS_EXPORT: "settings:salesSettings:export",

  SETTINGS_PURCHASE_SETTINGS_VIEW: "settings:purchaseSettings:view",
  SETTINGS_PURCHASE_SETTINGS_CREATE: "settings:purchaseSettings:create",
  SETTINGS_PURCHASE_SETTINGS_EDIT: "settings:purchaseSettings:edit",
  SETTINGS_PURCHASE_SETTINGS_APPROVE: "settings:purchaseSettings:approve",
  SETTINGS_PURCHASE_SETTINGS_DELETE: "settings:purchaseSettings:delete",
  SETTINGS_PURCHASE_SETTINGS_EXPORT: "settings:purchaseSettings:export",

  SETTINGS_PRODUCT_VIEW: "settings:product:view",
  SETTINGS_PRODUCT_CREATE: "settings:product:create",
  SETTINGS_PRODUCT_EDIT: "settings:product:edit",
  SETTINGS_PRODUCT_APPROVE: "settings:product:approve",
  SETTINGS_PRODUCT_DELETE: "settings:product:delete",
  SETTINGS_PRODUCT_EXPORT: "settings:product:export",

  SETTINGS_TAX_VIEW: "settings:tax:view",
  SETTINGS_TAX_CREATE: "settings:tax:create",
  SETTINGS_TAX_EDIT: "settings:tax:edit",
  SETTINGS_TAX_APPROVE: "settings:tax:approve",
  SETTINGS_TAX_DELETE: "settings:tax:delete",
  SETTINGS_TAX_EXPORT: "settings:tax:export",

  SETTINGS_GENERAL_SETTINGS_VIEW: "settings:generalSettings:view",
  SETTINGS_GENERAL_SETTINGS_CREATE: "settings:generalSettings:create",
  SETTINGS_GENERAL_SETTINGS_EDIT: "settings:generalSettings:edit",
  SETTINGS_GENERAL_SETTINGS_APPROVE: "settings:generalSettings:approve",
  SETTINGS_GENERAL_SETTINGS_DELETE: "settings:generalSettings:delete",
  SETTINGS_GENERAL_SETTINGS_EXPORT: "settings:generalSettings:export",

  SETTINGS_EMAIL_SETTINGS_VIEW: "settings:emailSettings:view",
  SETTINGS_EMAIL_SETTINGS_CREATE: "settings:emailSettings:create",
  SETTINGS_EMAIL_SETTINGS_EDIT: "settings:emailSettings:edit",
  SETTINGS_EMAIL_SETTINGS_APPROVE: "settings:emailSettings:approve",
  SETTINGS_EMAIL_SETTINGS_DELETE: "settings:emailSettings:delete",
  SETTINGS_EMAIL_SETTINGS_EXPORT: "settings:emailSettings:export",

  // ADDED PAYROLL ADD TO BACKEND
  SETTINGS_PAYROLL_SETTINGS_VIEW: "settings:payrollSettings:view",
  SETTINGS_PAYROLL_SETTINGS_CREATE: "settings:payrollSettings:create",
  SETTINGS_PAYROLL_SETTINGS_EDIT: "settings:payrollSettings:edit",
  SETTINGS_PAYROLL_SETTINGS_APPROVE: "settings:payrollSettings:approve",
  SETTINGS_PAYROLL_SETTINGS_DELETE: "settings:payrollSettings:delete",
  SETTINGS_PAYROLL_SETTINGS_EXPORT: "settings:payrollSettings:export",
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
