export const itemCategories = [
  "Professional Services",
  "Creative Services",
  "Training",
  "Digital Products",
  "Consulting",
  "Support and Maintenance",
  "Marketing",
  "Design",
  "Development",
] as const;

export const itemTypes = ["service", "goods"] as const;

// Mock data for items
export const mockItemsData = {
  items: [
    {
      id: "1",
      code: "SRV-CONS-001",
      name: "Consulting Services",
      description: "Professional consulting and advisory services",
      type: "service" as const,
      category: "Professional Services",
      unitPrice: 50000,
      incomeAccountId: "4100",
      incomeAccountName: "4100 - Service Revenue",
      isTaxable: true,
      isActive: true,
      entityId: "1",
    },
    {
      id: "2",
      code: "SRV-WEB-001",
      name: "Web Design",
      description: "Custom website design and development",
      type: "Service" as const,
      category: "Creative Services",
      unitPrice: 75000,
      incomeAccountId: "4100",
      incomeAccountName: "4100 - Service Revenue",
      isTaxable: true,
      isActive: true,
      entityId: "1",
    },
    {
      id: "3",
      code: "SRV-TRN-001",
      name: "Training Session",
      description: "Professional training and workshops",
      type: "Service" as const,
      category: "Training",
      unitPrice: 35000,
      incomeAccountId: "4100",
      incomeAccountName: "4100 - Service Revenue",
      isTaxable: true,
      isActive: true,
      entityId: "1",
    },
    {
      id: "4",
      code: "GDS-SFT-001",
      name: "Software License",
      description: "Annual software license subscription",
      type: "Good" as const,
      category: "Digital Products",
      unitPrice: 120000,
      incomeAccountId: "4200",
      incomeAccountName: "4200 - Product Sales",
      isTaxable: false,
      isActive: true,
      entityId: "1",
    },
    {
      id: "5",
      code: "SRV-SUP-001",
      name: "Support Package",
      description: "24/7 technical support and maintenance",
      type: "Service" as const,
      category: "Support and Maintenance",
      unitPrice: 45000,
      incomeAccountId: "4100",
      incomeAccountName: "4100 - Service Revenue",
      isTaxable: true,
      isActive: true,
      entityId: "1",
    },
    {
      id: "6",
      code: "GDS-DOC-001",
      name: "Documentation",
      description: "Technical documentation and guides",
      type: "Good" as const,
      category: "Digital Products",
      unitPrice: 25000,
      incomeAccountId: "4200",
      incomeAccountName: "4200 - Product Sales",
      isTaxable: false,
      isActive: false,
      entityId: "1",
    },
  ],
  total: 6,
  totalServices: 4,
  totalGoods: 2,
  averagePrice: 55000,
};
