// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import {
  defineConfig,
  // env
} from 'prisma/config';

// console.log('DATABASE_URL:', env('DATABASE_URL'));

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url:
      process.env.DATABASE_URL ??
      'postgresql://postgres:postgres@localhost:5432/xfinance?schema=public',

    // url:
    //   env('DATABASE_URL') ??
    //   'postgresql://postgres:postgres@localhost:5432/xfinance?schema=public',
  },
});
